In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


TENSOR

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
#check dimension
vector.ndim

1

In [ ]:
#check shape
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

###RANDOM TENSOR


In [ ]:
random_tensor= torch.rand(3,4)
random_tensor


tensor([[0.7995, 0.1833, 0.8662, 0.7168],
        [0.9083, 0.1759, 0.0523, 0.1266],
        [0.4941, 0.8834, 0.2992, 0.8647]])

In [ ]:
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tensor and tensor-like
torch.arange(start, end, step)


start → starting value (included)
end → ending value (not included)
step → gap between numbers

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Tensor datatypes
default datatype is float 32
device can be cuda

**Note: Tensor dataype is one of the 3 big issues you will find in pytord and in deep learning
1. Tensor of not right shape
2. dtype
3. right device

In [ ]:
#Float 32 tensor
Float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype= None
                               , device =None #what device is tensor on
                               , requires_grad=False # wether or not to use tensor to track gradeint
                               )
Float_32_tensor


tensor([3., 6., 9.])

In [ ]:
Float_32_tensor.dtype

torch.float32

In [ ]:
Float_16_tensor= Float_32_tensor.type(torch.float16)
Float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

###Getting Inforamtion from tensor

`tensor.dtype`,
`tensor.shape` = `tensor.size()`,
`tensor.device`


###Manipulating tensor (tensor operation)